name: release
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'release' || 'test' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: tools/ci/release.sh ${{ github.ref == 'refs/heads/main' && '--' || '--dry-run' }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
